package StringModule;


/**
* StringModule/StringOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Monday, April 28, 2025 1:28:29 PM UTC
*/

public interface StringOperation extends StringOperationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperation
