package StringModule;

/**
* StringModule/StringOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Tuesday, April 29, 2025 2:33:51 AM UTC
*/

public final class StringOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public StringModule.StringOperation value = null;

  public StringOperationHolder ()
  {
  }

  public StringOperationHolder (StringModule.StringOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringModule.StringOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringModule.StringOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringModule.StringOperationHelper.type ();
  }

}
