package StringModule;


/**
* StringModule/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Monday, April 28, 2025 1:28:29 PM UTC
*/

public interface StringOperationOperations 
{
  String reverseString (String input);
  String uppercaseString (String input);
} // interface StringOperationOperations
