package StringModule;


/**
* StringModule/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Tuesday, April 29, 2025 2:33:51 AM UTC
*/

public interface StringOperationOperations 
{
  String reverseString (String input);
  String uppercaseString (String input);
} // interface StringOperationOperations
