package stringmodule;

/**
* stringmodule/StringOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stringop.idl
* Tuesday, April 29, 2025 2:28:33 AM UTC
*/

public final class StringOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public stringmodule.StringOperation value = null;

  public StringOperationHolder ()
  {
  }

  public StringOperationHolder (stringmodule.StringOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = stringmodule.StringOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    stringmodule.StringOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return stringmodule.StringOperationHelper.type ();
  }

}
