package stringmodule;


/**
* stringmodule/StringOperationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stringop.idl
* Tuesday, April 29, 2025 2:28:33 AM UTC
*/

abstract public class StringOperationHelper
{
  private static String  _id = "IDL:stringmodule/StringOperation:1.0";

  public static void insert (org.omg.CORBA.Any a, stringmodule.StringOperation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static stringmodule.StringOperation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (stringmodule.StringOperationHelper.id (), "StringOperation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static stringmodule.StringOperation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StringOperationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, stringmodule.StringOperation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static stringmodule.StringOperation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof stringmodule.StringOperation)
      return (stringmodule.StringOperation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      stringmodule._StringOperationStub stub = new stringmodule._StringOperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static stringmodule.StringOperation unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof stringmodule.StringOperation)
      return (stringmodule.StringOperation)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      stringmodule._StringOperationStub stub = new stringmodule._StringOperationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
