package stringmodule;


/**
* stringmodule/StringOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stringop.idl
* Tuesday, April 29, 2025 2:28:33 AM UTC
*/

public interface StringOperation extends StringOperationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperation
