package stringmodule;


/**
* stringmodule/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stringop.idl
* Tuesday, April 29, 2025 2:28:33 AM UTC
*/

public interface StringOperationOperations 
{
  String revStr (String input);
} // interface StringOperationOperations
